<%@ page import="java.io.*,java.nio.charset.StandardCharsets,java.nio.file.*,java.nio.file.attribute.BasicFileAttributes,java.util.*,com.nortel.eem.em.security.EdmSecurity,com.nortel.eem.em.security.AuditLog" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
private static final Path ROOT=Paths.get("/opt/fabricnavigator/data"),SETTINGS=ROOT.resolve("acli-settings.properties"),CONFIG=ROOT.resolve("acli.ini"),LOG_ROOT=ROOT.resolve("acli-logs");
private static String h(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private static int number(String raw,int fallback,int min,int max){try{int value=Integer.parseInt(raw==null?"":raw.trim());if(value<min||value>max)throw new NumberFormatException();return value;}catch(Exception ex){return fallback;}}
private static boolean enabled(Properties p,String key,boolean fallback){return "true".equalsIgnoreCase(p.getProperty(key,Boolean.toString(fallback)));}
private static Properties loadSettings(){Properties p=new Properties();if(Files.isRegularFile(SETTINGS))try(InputStream in=Files.newInputStream(SETTINGS)){p.load(in);}catch(Exception ignored){}return p;}
private static synchronized void atomicProperties(Properties p)throws IOException{Files.createDirectories(ROOT);Path tmp=Files.createTempFile(ROOT,"acli-settings.",".tmp");try{try(OutputStream out=Files.newOutputStream(tmp)){p.store(out,"FabricNavigator managed ACLI settings");}try{Files.move(tmp,SETTINGS,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ex){Files.move(tmp,SETTINGS,StandardCopyOption.REPLACE_EXISTING);}}finally{Files.deleteIfExists(tmp);}}
private static synchronized void writeConfig(Properties p)throws IOException{Files.createDirectories(ROOT);Files.createDirectories(LOG_ROOT);List<String> lines=Arrays.asList(
"##############################","# FabricNavigator ACLI config #","##############################","# Version = 999","",
"timeout_val\t\t\t"+p.getProperty("timeoutVal","22"),"connect_timeout_val\t\t"+p.getProperty("connectTimeoutVal","35"),"login_timeout_val\t\t"+p.getProperty("loginTimeoutVal","30"),
"auto_detect_flg\t\t\t"+(enabled(p,"autoDetect",true)?"1":"0"),"more_paging_flg\t\t"+(enabled(p,"morePaging",true)?"1":"0"),"alias_enable_flg\t\t"+(enabled(p,"aliasEnable",true)?"1":"0"),
"keepalive_timer_val\t\t"+p.getProperty("keepaliveTimerVal","4"),"session_timeout_val\t\t"+p.getProperty("sessionTimeoutVal","600"),
"auto_log_to_file_flg\t\t"+(enabled(p,"autoLog",false)?"1":"0"),"log_path_str\t\t\t'"+LOG_ROOT.toString().replace("'","")+"'","auto_log_filename_str\t\t'%Y/%m/%d/%H-%M-%S_<>'","");
Path tmp=Files.createTempFile(ROOT,"acli.",".tmp");try{Files.write(tmp,lines,StandardCharsets.UTF_8);try{Files.move(tmp,CONFIG,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ex){Files.move(tmp,CONFIG,StandardCopyOption.REPLACE_EXISTING);}}finally{Files.deleteIfExists(tmp);}}
private static List<Path> logs()throws IOException{final List<Path> result=new ArrayList<Path>();if(!Files.isDirectory(LOG_ROOT))return result;Files.walkFileTree(LOG_ROOT,new SimpleFileVisitor<Path>(){public FileVisitResult visitFile(Path file,BasicFileAttributes attrs){String n=file.getFileName().toString().toLowerCase(Locale.ROOT);if(n.endsWith(".txt")||n.endsWith(".log"))result.add(file);return FileVisitResult.CONTINUE;}});Collections.sort(result,new Comparator<Path>(){public int compare(Path a,Path b){try{return Long.compare(Files.getLastModifiedTime(b).toMillis(),Files.getLastModifiedTime(a).toMillis());}catch(Exception ex){return 0;}}});return result.size()>250?new ArrayList<Path>(result.subList(0,250)):result;}
private static Path safeLog(String relative)throws IOException{if(relative==null||relative.length()==0)throw new FileNotFoundException();Path target=LOG_ROOT.resolve(relative).normalize();if(!target.startsWith(LOG_ROOT)||!Files.isRegularFile(target))throw new FileNotFoundException();return target;}
private static void clearLogs()throws IOException{if(!Files.isDirectory(LOG_ROOT))return;Files.walkFileTree(LOG_ROOT,new SimpleFileVisitor<Path>(){public FileVisitResult visitFile(Path file,BasicFileAttributes attrs)throws IOException{Files.deleteIfExists(file);return FileVisitResult.CONTINUE;}public FileVisitResult postVisitDirectory(Path dir,IOException error)throws IOException{if(!dir.equals(LOG_ROOT))Files.deleteIfExists(dir);return FileVisitResult.CONTINUE;}});}
private static String size(long value){if(value<1024)return value+" B";if(value<1048576)return String.format(Locale.ROOT,"%.1f KB",value/1024.0);return String.format(Locale.ROOT,"%.1f MB",value/1048576.0);}
%><%
if(!EdmSecurity.isAdmin(request)){response.sendError(403);return;}response.setHeader("Cache-Control","no-store");
String download=request.getParameter("download");if(download!=null){try{Path file=safeLog(download);response.setContentType("text/plain; charset=UTF-8");response.setHeader("Content-Disposition","attachment; filename=\""+file.getFileName().toString().replace("\"","")+"\"");Files.copy(file,response.getOutputStream());return;}catch(Exception ex){response.sendError(404);return;}}
String csrf=EdmSecurity.csrf(session),flash="",error="";Properties values=loadSettings();
if("POST".equalsIgnoreCase(request.getMethod())){if(!EdmSecurity.validCsrf(request)){response.sendError(403);return;}String action=request.getParameter("action");try{
 if("save".equals(action)){Properties next=new Properties();next.setProperty("timeoutVal",Integer.toString(number(request.getParameter("timeoutVal"),22,1,600)));next.setProperty("connectTimeoutVal",Integer.toString(number(request.getParameter("connectTimeoutVal"),35,1,300)));next.setProperty("loginTimeoutVal",Integer.toString(number(request.getParameter("loginTimeoutVal"),30,1,300)));next.setProperty("keepaliveTimerVal",Integer.toString(number(request.getParameter("keepaliveTimerVal"),4,0,120)));next.setProperty("sessionTimeoutVal",Integer.toString(number(request.getParameter("sessionTimeoutVal"),600,0,10080)));for(String key:Arrays.asList("autoDetect","morePaging","aliasEnable","autoLog"))next.setProperty(key,Boolean.toString("true".equals(request.getParameter(key))));atomicProperties(next);writeConfig(next);values=next;AuditLog.log(EdmSecurity.currentUser(request),"ACLI_SETTINGS_UPDATE","autoLog="+next.getProperty("autoLog"),request.getRemoteAddr());flash="ACLI-Einstellungen gespeichert. Neue Sitzungen verwenden die Änderungen sofort.";}
 else if("deleteLog".equals(action)){Path file=safeLog(request.getParameter("log"));Files.delete(file);AuditLog.log(EdmSecurity.currentUser(request),"ACLI_LOG_DELETE",file.getFileName().toString(),request.getRemoteAddr());flash="Sitzungsprotokoll gelöscht.";}
 else if("clearLogs".equals(action)){clearLogs();AuditLog.log(EdmSecurity.currentUser(request),"ACLI_LOG_CLEAR","all",request.getRemoteAddr());flash="Alle ACLI-Sitzungsprotokolle wurden gelöscht.";}
 else throw new IllegalArgumentException();
}catch(Exception ex){error="Die ACLI-Einstellung konnte nicht gespeichert oder ausgeführt werden.";}}
boolean autoLog=enabled(values,"autoLog",false),autoDetect=enabled(values,"autoDetect",true),morePaging=enabled(values,"morePaging",true),aliasEnable=enabled(values,"aliasEnable",true);List<Path> logFiles=Collections.emptyList();try{logFiles=logs();}catch(Exception ex){error="Die Sitzungsprotokolle konnten nicht gelesen werden.";}
%><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ACLI</title><link rel="stylesheet" href="/assets/security.css?v=20260831-179"><style>html,body{width:100%;max-width:100%;overflow-x:hidden;background:transparent}body{margin:0;padding:2px;display:grid;gap:18px}.card{min-width:0;background:#fff;border:1px solid #b66cff;border-radius:18px;padding:24px;box-shadow:0 16px 35px -30px #31105f}.secret-note{background:#f5f0ff;border-left:4px solid #8d25e8;padding:12px;line-height:1.55}.settings{display:grid;grid-template-columns:repeat(3,minmax(160px,1fr));gap:16px;margin:20px 0}.settings label{display:grid;gap:7px;font-weight:800}.flags{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:10px;margin:18px 0}.flags label{display:flex;gap:10px;align-items:center;padding:12px;border:1px solid #ddd2ef;border-radius:12px;font-weight:800}.flags input{width:auto}.hint{color:#667085;font-size:13px;line-height:1.5}.actions{display:flex;gap:10px;justify-content:flex-end;flex-wrap:wrap}.alert{padding:12px;border-radius:10px}.success{background:#e8f8ee;color:#176b36}.error{background:#fdecec;color:#8d1f25}.log-table{width:100%;border-collapse:collapse;font-size:13px}.log-table th,.log-table td{padding:10px;border-bottom:1px solid #e5e7ef;text-align:left}.log-path{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.log-actions{display:flex;gap:8px}.muted{background:#fff!important;color:#6419aa!important;border:1px solid #c9a9ed!important}.danger{background:#a4262c!important}.scroll{max-width:100%;overflow-x:auto;overflow-y:visible}[data-theme=dark] .card{background:#151c2e;color:#eef1f7}[data-theme=dark] .secret-note{background:#231b38}[data-theme=dark] .hint{color:#aab3c5}[data-theme=dark] .flags label{border-color:#46516a;background:#11192a}[data-theme=dark] .log-table th,[data-theme=dark] .log-table td{border-color:#3e4960}[data-theme=dark] .muted{background:#11192a!important;color:#dcc4fa!important}@media(max-width:800px){.settings{grid-template-columns:1fr 1fr}.flags{grid-template-columns:1fr}}@media(max-width:520px){.settings{grid-template-columns:1fr}}</style></head><body>
<%if(flash.length()>0){%><div class="alert success"><%=h(flash)%></div><%}if(error.length()>0){%><div class="alert error"><%=h(error)%></div><%}%>
<section class="card"><h2 data-de="ACLI-Einstellungen" data-en="ACLI settings">ACLI-Einstellungen</h2><p class="secret-note" data-de="Verwalte eine geprüfte Auswahl globaler acli.ini-Parameter. Änderungen gelten für neu geöffnete SSH-Sitzungen; bestehende Sitzungen bleiben unverändert." data-en="Manage a validated selection of global acli.ini parameters. Changes apply to newly opened SSH sessions; existing sessions remain unchanged.">Verwalte eine geprüfte Auswahl globaler acli.ini-Parameter.</p><form method="post"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><input type="hidden" name="action" value="save"><div class="settings">
<label><span data-de="Befehls-Timeout (s)" data-en="Command timeout (s)">Befehls-Timeout (s)</span><input type="number" name="timeoutVal" min="1" max="600" value="<%=number(values.getProperty("timeoutVal"),22,1,600)%>"></label><label><span data-de="Verbindungs-Timeout (s)" data-en="Connection timeout (s)">Verbindungs-Timeout (s)</span><input type="number" name="connectTimeoutVal" min="1" max="300" value="<%=number(values.getProperty("connectTimeoutVal"),35,1,300)%>"></label><label><span data-de="Login-Timeout (s)" data-en="Login timeout (s)">Login-Timeout (s)</span><input type="number" name="loginTimeoutVal" min="1" max="300" value="<%=number(values.getProperty("loginTimeoutVal"),30,1,300)%>"></label><label><span data-de="Keepalive (Minuten)" data-en="Keepalive (minutes)">Keepalive (Minuten)</span><input type="number" name="keepaliveTimerVal" min="0" max="120" value="<%=number(values.getProperty("keepaliveTimerVal"),4,0,120)%>"></label><label><span data-de="Sitzungs-Timeout (Minuten)" data-en="Session timeout (minutes)">Sitzungs-Timeout (Minuten)</span><input type="number" name="sessionTimeoutVal" min="0" max="10080" value="<%=number(values.getProperty("sessionTimeoutVal"),600,0,10080)%>"></label></div><div class="flags">
<label><input type="checkbox" name="autoDetect" value="true" <%=autoDetect?"checked":""%>><span data-de="Gerätetyp automatisch erkennen" data-en="Automatically detect device type">Gerätetyp automatisch erkennen</span></label><label><input type="checkbox" name="morePaging" value="true" <%=morePaging?"checked":""%>><span data-de="Lokales More-Paging" data-en="Local more paging">Lokales More-Paging</span></label><label><input type="checkbox" name="aliasEnable" value="true" <%=aliasEnable?"checked":""%>><span data-de="ACLI-Aliase aktivieren" data-en="Enable ACLI aliases">ACLI-Aliase aktivieren</span></label><label><input type="checkbox" name="autoLog" value="true" <%=autoLog?"checked":""%>><span data-de="Sitzungen automatisch protokollieren (auto_log_to_file_flg)" data-en="Automatically log sessions (auto_log_to_file_flg)">Sitzungen automatisch protokollieren</span></label></div><p class="hint" data-de="Protokollstruktur: Jahr/Monat/Tag/Uhrzeit_Geräte-IP.txt. Die Dateien können Konfigurationen und eingegebene Kommandos enthalten und sind deshalb nur für Administratoren verfügbar." data-en="Log structure: year/month/day/time_device-IP.txt. Files may contain configurations and entered commands and are therefore restricted to administrators.">Protokollstruktur: Jahr/Monat/Tag/Uhrzeit_Geräte-IP.txt.</p><div class="actions"><button type="submit" data-de="ACLI-Einstellungen speichern" data-en="Save ACLI settings">ACLI-Einstellungen speichern</button></div></form></section>
<section class="card"><h2 data-de="ACLI-Sitzungsprotokolle" data-en="ACLI session logs">ACLI-Sitzungsprotokolle</h2><p class="secret-note" data-de="Die neuesten 250 Protokolle werden angezeigt. Aktive Sitzungen können vorübergehend die Endung .log besitzen und werden beim Sitzungsende in .txt umbenannt." data-en="The newest 250 logs are shown. Active sessions may temporarily use the .log extension and are renamed to .txt when the session ends.">Die neuesten 250 Protokolle werden angezeigt.</p><%if(logFiles.isEmpty()){%><p class="hint" data-de="Noch keine Sitzungsprotokolle vorhanden." data-en="No session logs are available yet.">Noch keine Sitzungsprotokolle vorhanden.</p><%}else{%><div class="scroll"><table class="log-table"><thead><tr><th data-de="Datei" data-en="File">Datei</th><th data-de="Geändert" data-en="Modified">Geändert</th><th data-de="Größe" data-en="Size">Größe</th><th data-de="Aktionen" data-en="Actions">Aktionen</th></tr></thead><tbody><%for(Path file:logFiles){String relative=LOG_ROOT.relativize(file).toString().replace(File.separatorChar,'/');%><tr><td class="log-path"><%=h(relative)%></td><td><%=new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(Files.getLastModifiedTime(file).toMillis()))%></td><td><%=h(size(Files.size(file)))%></td><td><div class="log-actions"><a class="button muted" href="/admin/acli-settings.jsp?download=<%=java.net.URLEncoder.encode(relative,"UTF-8")%>" data-de="Herunterladen" data-en="Download">Herunterladen</a><form method="post"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><input type="hidden" name="action" value="deleteLog"><input type="hidden" name="log" value="<%=h(relative)%>"><button class="danger" type="submit" data-de="Löschen" data-en="Delete">Löschen</button></form></div></td></tr><%}%></tbody></table></div><form method="post" class="actions"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><input type="hidden" name="action" value="clearLogs"><button class="danger" type="submit" data-de="Alle Protokolle löschen" data-en="Delete all logs">Alle Protokolle löschen</button></form><%}%></section>
<script>(function(){var lang='de';try{lang=localStorage.getItem('edmLanguage')||'de';document.documentElement.lang=lang;document.documentElement.setAttribute('data-theme',localStorage.getItem('edmTheme')||'light');}catch(e){}document.querySelectorAll('[data-de]').forEach(function(node){node.textContent=node.getAttribute(lang==='en'?'data-en':'data-de');});}());</script></body></html>
