<%@ page import="java.io.*,java.nio.charset.StandardCharsets,java.nio.file.*,java.util.*,com.nortel.eem.em.security.EdmSecurity,com.nortel.eem.em.security.AuditLog" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
private static final Path EXCLUDES=Paths.get("/opt/fabricnavigator/data/discovery-excludes.txt");
private static final Path SETTINGS=Paths.get("/opt/fabricnavigator/data/discovery.properties");
private static final Path DISCOVERY_LOG=Paths.get("/opt/fabricnavigator/data/discovery.log");
private static final int DEFAULT_TIMEOUT_MS=2500,MIN_TIMEOUT_MS=500,MAX_TIMEOUT_MS=30000,DEFAULT_RETRIES=0,MIN_RETRIES=0,MAX_RETRIES=5;
private static String h(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private static boolean privateIp(String value){if(value==null||!value.matches("^[0-9.]{7,15}$"))return false;String[] p=value.split("\\.",-1);if(p.length!=4)return false;int[] o=new int[4];for(int i=0;i<4;i++)try{o[i]=Integer.parseInt(p[i]);if(o[i]<0||o[i]>255)return false;}catch(Exception ex){return false;}return o[0]==10||(o[0]==172&&o[1]>=16&&o[1]<=31)||(o[0]==192&&o[1]==168);}
private static LinkedHashSet<String> parseRules(String input){LinkedHashSet<String> out=new LinkedHashSet<String>();if(input==null)return out;for(String token:input.split("[,\\r\\n]+")){String rule=token.trim();if(rule.length()==0)continue;String ip=rule;int prefix=32,slash=rule.indexOf('/');if(slash>=0){ip=rule.substring(0,slash).trim();try{prefix=Integer.parseInt(rule.substring(slash+1).trim());}catch(Exception ex){throw new IllegalArgumentException("invalidRule");}}if(!privateIp(ip)||prefix<8||prefix>32)throw new IllegalArgumentException("invalidRule");out.add(ip+(prefix==32?"":"/"+prefix));if(out.size()>256)throw new IllegalArgumentException("tooManyRules");}return out;}
private static int boundedInt(String value,int minimum,int maximum,String error){try{int parsed=Integer.parseInt(value==null?"":value.trim());if(parsed<minimum||parsed>maximum)throw new NumberFormatException();return parsed;}catch(Exception ex){throw new IllegalArgumentException(error);}}
private static synchronized void saveRules(Collection<String> rules)throws IOException{Files.createDirectories(EXCLUDES.getParent());Path tmp=Files.createTempFile(EXCLUDES.getParent(),"discovery-excludes.",".tmp");try{Files.write(tmp,rules,StandardCharsets.UTF_8);try{Files.move(tmp,EXCLUDES,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ex){Files.move(tmp,EXCLUDES,StandardCopyOption.REPLACE_EXISTING);}}finally{Files.deleteIfExists(tmp);}}
private static synchronized void saveSettings(int timeoutMs,int retries)throws IOException{Files.createDirectories(SETTINGS.getParent());Properties values=new Properties();values.setProperty("snmpTimeoutMs",Integer.toString(timeoutMs));values.setProperty("snmpRetries",Integer.toString(retries));Path tmp=Files.createTempFile(SETTINGS.getParent(),"discovery.",".tmp");try{try(OutputStream out=Files.newOutputStream(tmp)){values.store(out,"FabricNavigator discovery settings");}try{Files.move(tmp,SETTINGS,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ex){Files.move(tmp,SETTINGS,StandardCopyOption.REPLACE_EXISTING);}}finally{Files.deleteIfExists(tmp);}}
private static Properties currentSettings(){Properties values=new Properties();if(Files.isRegularFile(SETTINGS))try(InputStream in=Files.newInputStream(SETTINGS)){values.load(in);}catch(Exception ignored){}return values;}
private static int setting(Properties values,String name,int fallback,int minimum,int maximum){try{int value=Integer.parseInt(values.getProperty(name,Integer.toString(fallback)));return Math.max(minimum,Math.min(maximum,value));}catch(Exception ex){return fallback;}}
private static String currentRules()throws IOException{return Files.isRegularFile(EXCLUDES)?new String(Files.readAllBytes(EXCLUDES),StandardCharsets.UTF_8).trim():"";}
private static String currentLog()throws IOException{if(!Files.isRegularFile(DISCOVERY_LOG))return "";byte[] bytes=Files.readAllBytes(DISCOVERY_LOG);int start=Math.max(0,bytes.length-262144);return new String(bytes,start,bytes.length-start,StandardCharsets.UTF_8).trim();}
%>
<%
if(!EdmSecurity.isAdmin(request)){response.sendError(403);return;}
response.setHeader("Cache-Control","no-store");
if("1".equals(request.getParameter("download"))){response.setContentType("text/plain; charset=UTF-8");response.setHeader("Content-Disposition","attachment; filename=FabricNavigator-discovery.log");if(Files.isRegularFile(DISCOVERY_LOG))out.write(new String(Files.readAllBytes(DISCOVERY_LOG),StandardCharsets.UTF_8));return;}
String csrf=EdmSecurity.csrf(session),flash="",error="";
Properties settings=currentSettings();
int timeoutMs=setting(settings,"snmpTimeoutMs",DEFAULT_TIMEOUT_MS,MIN_TIMEOUT_MS,MAX_TIMEOUT_MS),retries=setting(settings,"snmpRetries",DEFAULT_RETRIES,MIN_RETRIES,MAX_RETRIES);
if("POST".equalsIgnoreCase(request.getMethod())){
    if(!EdmSecurity.validCsrf(request)){response.sendError(403);return;}
    try{if("clearLog".equals(request.getParameter("action"))){Files.deleteIfExists(DISCOVERY_LOG);AuditLog.log(EdmSecurity.currentUser(request),"DISCOVERY_LOG_CLEAR","Discovery log cleared",request.getRemoteAddr());flash="Discovery-Protokoll gelöscht.";}else{
        LinkedHashSet<String> rules=parseRules(request.getParameter("excludeRules"));
        timeoutMs=boundedInt(request.getParameter("snmpTimeoutMs"),MIN_TIMEOUT_MS,MAX_TIMEOUT_MS,"invalidTimeout");
        retries=boundedInt(request.getParameter("snmpRetries"),MIN_RETRIES,MAX_RETRIES,"invalidRetries");
        saveRules(rules);saveSettings(timeoutMs,retries);
        AuditLog.log(EdmSecurity.currentUser(request),"DISCOVERY_SETTINGS_UPDATE",rules.size()+" excludes, timeout="+timeoutMs+"ms, retries="+retries,request.getRemoteAddr());
        flash="Discovery-Einstellungen gespeichert.";
    }}catch(IllegalArgumentException ex){
        if("invalidTimeout".equals(ex.getMessage()))error="Der SNMP-Timeout muss zwischen 500 und 30000 Millisekunden liegen.";
        else if("invalidRetries".equals(ex.getMessage()))error="Die SNMP-Wiederholungen müssen zwischen 0 und 5 liegen.";
        else error="Ungültige Ausschlussregel. Verwende private IPv4-Adressen oder CIDR-Netze, zum Beispiel 192.168.1.50 oder 192.168.20.0/24.";
    }catch(Exception ex){error="Die Discovery-Einstellungen konnten nicht gespeichert werden.";}
}
String rules="";try{rules=currentRules();}catch(Exception ex){error="Die Discovery-Einstellungen konnten nicht geladen werden.";}
String discoveryLog="";try{discoveryLog=currentLog();}catch(Exception ex){error="Das Discovery-Protokoll konnte nicht geladen werden.";}
%>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Discovery</title><link rel="stylesheet" href="/assets/security.css?v=20260831-172"><style>html,body{background:transparent}body{margin:0;padding:2px;display:grid;gap:18px}.card{background:#fff;border:1px solid #b66cff;border-radius:18px;padding:24px;box-shadow:0 16px 35px -30px #31105f}.settings-grid{display:grid;grid-template-columns:repeat(2,minmax(180px,1fr));gap:16px;margin:20px 0}label{display:grid;gap:8px;font-weight:800}input[type=number],textarea{box-sizing:border-box;width:100%;border:1px solid #c9ceda;border-radius:10px;padding:12px;font:14px/1.5 Arial,Helvetica,sans-serif}textarea{min-height:220px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.hint{color:#667085;font-size:13px;line-height:1.55}.secret-note{background:#f5f0ff;border-left:4px solid #8d25e8;padding:12px}.alert{padding:12px;border-radius:10px;margin-bottom:14px}.success{background:#e8f8ee;color:#176b36}.error{background:#fdecec;color:#8d1f25}.actions{display:flex;gap:10px;justify-content:flex-end;margin-top:14px}.actions a{display:inline-flex;align-items:center;text-decoration:none}.discovery-log{box-sizing:border-box;width:100%;min-height:300px;max-height:600px;overflow:auto;white-space:pre-wrap;word-break:break-word;margin:16px 0 0;padding:16px;border:1px solid #c9ceda;border-radius:12px;background:#f7f8fb;color:#162033;font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}[data-theme=dark] .card{background:#151c2e;color:#eef1f7}[data-theme=dark] input[type=number],[data-theme=dark] textarea{background:#0f1628;border-color:#46516a;color:#eef1f7}[data-theme=dark] .hint{color:#aab3c5}[data-theme=dark] .secret-note{background:#231b38}[data-theme=dark] .discovery-log{background:#0f1628;border-color:#46516a;color:#dbe5f4}@media(max-width:650px){.settings-grid{grid-template-columns:1fr}.actions{justify-content:stretch;flex-direction:column}}</style></head><body>
<%if(flash.length()>0){%><div class="alert success"><%=h(flash)%></div><%}if(error.length()>0){%><div class="alert error"><%=h(error)%></div><%}%>
<section class="card"><h2 data-de="Discovery-Einstellungen" data-en="Discovery settings">Discovery-Einstellungen</h2><p class="secret-note" data-de="Lege fest, wie lange FabricNavigator auf eine SNMP-Antwort wartet und wie oft eine fehlgeschlagene Abfrage zusätzlich wiederholt wird." data-en="Configure how long FabricNavigator waits for an SNMP response and how often a failed request is retried.">Lege fest, wie lange FabricNavigator auf eine SNMP-Antwort wartet und wie oft eine fehlgeschlagene Abfrage zusätzlich wiederholt wird.</p>
<form method="post"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><div class="settings-grid"><label><span data-de="SNMP-Timeout (Millisekunden)" data-en="SNMP timeout (milliseconds)">SNMP-Timeout (Millisekunden)</span><input type="number" name="snmpTimeoutMs" min="500" max="30000" step="100" required value="<%=timeoutMs%>"><span class="hint" data-de="Zulässig: 500 bis 30000 ms. Ein höherer Wert hilft bei langsamen oder entfernten Geräten, verlängert aber die Discovery." data-en="Allowed: 500 to 30000 ms. A higher value helps with slow or remote devices but increases discovery time.">Zulässig: 500 bis 30000 ms.</span></label><label><span data-de="SNMP-Wiederholungen" data-en="SNMP retries">SNMP-Wiederholungen</span><input type="number" name="snmpRetries" min="0" max="5" step="1" required value="<%=retries%>"><span class="hint" data-de="Zulässig: 0 bis 5 zusätzliche Versuche pro Zugangsdatenprofil und Gerät." data-en="Allowed: 0 to 5 additional attempts per credential profile and device.">Zulässig: 0 bis 5 zusätzliche Versuche.</span></label></div>
<h3 data-de="Discovery-Ausschlüsse" data-en="Discovery exclusions">Discovery-Ausschlüsse</h3><p class="secret-note" data-de="Ausgeschlossene IP-Adressen und Subnetze werden nicht in das Topologie-Ergebnis übernommen. Links zu ausgeschlossenen Geräten werden ebenfalls entfernt." data-en="Excluded IP addresses and subnets are omitted from topology results. Links to excluded devices are removed as well.">Ausgeschlossene IP-Adressen und Subnetze werden nicht in das Topologie-Ergebnis übernommen.</p><label><span data-de="IP-Adressen und CIDR-Subnetze" data-en="IP addresses and CIDR subnets">IP-Adressen und CIDR-Subnetze</span><textarea name="excludeRules" spellcheck="false" placeholder="192.168.1.50&#10;192.168.20.0/24"><%=h(rules)%></textarea></label><p class="hint" data-de="Eine Regel pro Zeile oder mit Komma trennen. Erlaubt sind bis zu 256 private IPv4-Adressen bzw. CIDR-Netze mit Präfix /8 bis /32." data-en="Enter one rule per line or separate rules with commas. Up to 256 private IPv4 addresses or CIDR networks with prefixes from /8 to /32 are allowed.">Eine Regel pro Zeile oder mit Komma trennen.</p><div class="actions"><button type="submit" data-de="Discovery-Einstellungen speichern" data-en="Save discovery settings">Discovery-Einstellungen speichern</button></div></form></section>
<section class="card"><h2 data-de="Discovery-Protokoll" data-en="Discovery log">Discovery-Protokoll</h2><p class="secret-note" data-de="Das Protokoll wird bei jeder Discovery ergänzt und enthält Geräteklassifikation, Entscheidungsgrund, SNMP-Gerätebeschreibung, Links, Warnungen und Laufzeit. Zugangsdaten und Geheimnisse werden nicht protokolliert." data-en="The log is extended after every discovery and contains device classification, decision reason, SNMP device description, links, warnings, and duration. Credentials and secrets are never logged.">Das Protokoll enthält die technischen Discovery-Details ohne Zugangsdaten.</p><%if(discoveryLog.length()>0){%><pre class="discovery-log"><%=h(discoveryLog)%></pre><div class="actions"><a class="button muted-button" href="/admin/discovery.jsp?download=1" data-de="Protokoll herunterladen" data-en="Download log">Protokoll herunterladen</a><form method="post"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><input type="hidden" name="action" value="clearLog"><button class="muted-button" type="submit" data-de="Protokoll löschen" data-en="Clear log">Protokoll löschen</button></form></div><%}else{%><p class="hint" data-de="Noch kein Discovery-Protokoll vorhanden. Starte eine Discovery in der Topologie." data-en="No discovery log is available yet. Start a discovery from Topology.">Noch kein Discovery-Protokoll vorhanden.</p><%}%></section>
<script>(function(){var lang='de';try{lang=localStorage.getItem('edmLanguage')||'de';var theme=localStorage.getItem('edmTheme')||'light';document.documentElement.lang=lang;document.documentElement.setAttribute('data-theme',theme);}catch(e){}document.querySelectorAll('[data-de]').forEach(function(node){node.textContent=node.getAttribute(lang==='en'?'data-en':'data-de');});}());</script></body></html>
