<%@ page import="com.nortel.eem.em.security.EdmSecurity,com.nortel.eem.em.security.AuditLog,java.io.*,java.nio.file.*,java.security.*,java.util.*,java.util.regex.*,java.util.zip.*" %><%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %><%!
private static final File STATE_DIR=new File(System.getenv("FABRICNAVIGATOR_UPDATE_DIR")!=null?System.getenv("FABRICNAVIGATOR_UPDATE_DIR"):"/opt/fabricnavigator/update");
private static final File OFFLINE_DIR=new File(STATE_DIR,"offline");
private static final Pattern VERSION=Pattern.compile("\\d+\\.\\d+\\.\\d+\\.\\d+");
private static final Pattern PLUGIN_VERSION=Pattern.compile("[A-Za-z0-9][A-Za-z0-9._-]{0,31}");
private static String j(String s){if(s==null)return"";return s.replace("\\","\\\\").replace("\"","\\\"").replace("\r","").replace("\n","\\n").replace("</","<\\/");}
private static String clean(String s){return s==null?"":s.replace("\r"," ").replace("\n"," ").replace("=","-").trim();}
private static void atomicProperties(File file,Properties values)throws Exception{file.getParentFile().mkdirs();File temporary=File.createTempFile(file.getName()+".",".tmp",file.getParentFile());Writer writer=new OutputStreamWriter(new FileOutputStream(temporary),"UTF-8");try{values.store(writer,"FabricNavigator offline package");}finally{writer.close();}try{Files.move(temporary.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException ex){Files.move(temporary.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING);}}
private static Properties properties(File file){Properties p=new Properties();if(!file.isFile())return p;try{InputStream in=new FileInputStream(file);try{p.load(new InputStreamReader(in,"UTF-8"));}finally{in.close();}}catch(Exception ignored){}return p;}
private static String hex(byte[] bytes){StringBuilder b=new StringBuilder();for(byte value:bytes)b.append(String.format("%02x",value&255));return b.toString();}
private static boolean safeEntry(String name){if(name==null)return false;String n=name.replace('\\','/');if(n.startsWith("/")||n.matches("^[A-Za-z]:.*"))return false;for(String part:n.split("/",-1))if("..".equals(part))return false;return true;}
private static byte[] readEntry(ZipFile zip,ZipEntry entry,int maximum)throws Exception{InputStream in=zip.getInputStream(entry);ByteArrayOutputStream out=new ByteArrayOutputStream();try{byte[] buffer=new byte[8192];int total=0,count;while((count=in.read(buffer))!=-1){total+=count;if(total>maximum)throw new IOException("Package metadata is too large.");out.write(buffer,0,count);}return out.toByteArray();}finally{in.close();}}
private static int[] versionParts(String value){String[] p=value.split("\\.");return new int[]{Integer.parseInt(p[0]),Integer.parseInt(p[1]),Integer.parseInt(p[2]),Integer.parseInt(p[3])};}
private static int compareVersion(String left,String right){int[] a=versionParts(left),b=versionParts(right);for(int i=0;i<4;i++){if(a[i]!=b[i])return a[i]<b[i]?-1:1;}return 0;}
private static String jsonField(String json,String name){Matcher m=Pattern.compile("\\\""+Pattern.quote(name)+"\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").matcher(json);return m.find()?m.group(1):"";}
private static long copyUpload(InputStream input,File target,long maximum,MessageDigest digest)throws Exception{OutputStream output=new FileOutputStream(target);long total=0;try{byte[] buffer=new byte[65536];int count;while((count=input.read(buffer))!=-1){total+=count;if(total>maximum)throw new IOException("The uploaded package exceeds the allowed size.");digest.update(buffer,0,count);output.write(buffer,0,count);}if(total<100)throw new IOException("The uploaded package is empty or incomplete.");return total;}finally{output.close();}}
private static void validateArchive(ZipFile zip)throws Exception{long total=0;int count=0;Enumeration<? extends ZipEntry> entries=zip.entries();while(entries.hasMoreElements()){ZipEntry entry=entries.nextElement();if(++count>4096)throw new IOException("The package contains too many files.");if(!safeEntry(entry.getName()))throw new IOException("Unsafe path in package: "+entry.getName());long size=entry.getSize();if(size>268435456L)throw new IOException("A package file exceeds the allowed size.");if(size>0){total+=size;if(total>1073741824L)throw new IOException("The unpacked package is too large.");}}}
%><%
response.setHeader("Cache-Control","no-store");response.setCharacterEncoding("UTF-8");if(!EdmSecurity.isAdmin(request)){response.sendError(403);return;}String kind=request.getParameter("kind");
if("GET".equalsIgnoreCase(request.getMethod())){Properties offline=properties(new File(STATE_DIR,"offline-update.properties")),plugin=properties(new File(STATE_DIR,"plugin-status.properties"));File installedManifest=new File("/opt/tomcat/webapps/ROOT/assets/product-switches/plugin.json");String installed="";try{if(installedManifest.isFile())installed=jsonField(new String(Files.readAllBytes(installedManifest.toPath()),"UTF-8"),"version");}catch(Exception ignored){}String pluginState=plugin.getProperty("state",installed.length()>0?"installed":"not-installed"),pluginVersion=plugin.getProperty("version",installed);if(installed.length()==0&&"installed".equals(pluginState))installed=pluginVersion;out.print("{\"offlineState\":\""+j(offline.getProperty("state","none"))+"\",\"offlineVersion\":\""+j(offline.getProperty("version",""))+"\",\"pluginState\":\""+j(pluginState)+"\",\"pluginVersion\":\""+j(pluginVersion)+"\",\"installedPluginVersion\":\""+j(installed)+"\",\"pluginMessage\":\""+j(plugin.getProperty("message",""))+"\"}");return;}
if(!"POST".equalsIgnoreCase(request.getMethod())||!EdmSecurity.validCsrf(request)){response.sendError(403);return;}if(!("core".equals(kind)||"images".equals(kind))){response.sendError(400);return;}
long maximum="core".equals(kind)?268435456L:536870912L,declared=request.getContentLengthLong();if(declared>maximum){response.sendError(413);return;}OFFLINE_DIR.mkdirs();File temporary=File.createTempFile("upload-",".zip",OFFLINE_DIR);String actor=EdmSecurity.currentUser(request);try{
 MessageDigest digest=MessageDigest.getInstance("SHA-256");long size=copyUpload(request.getInputStream(),temporary,maximum,digest);String sha=hex(digest.digest()),version="",targetName="";ZipFile zip=new ZipFile(temporary);try{validateArchive(zip);if("core".equals(kind)){ZipEntry manifest=zip.getEntry("runtime/core-overlay/manifest.properties"),compose=zip.getEntry("runtime/compose.yaml");if(manifest==null||compose==null)throw new IOException("The archive is not a FabricNavigator core update.");Properties values=new Properties();values.load(new InputStreamReader(zip.getInputStream(manifest),"UTF-8"));version=values.getProperty("targetVersion","").trim();if(!"core-overlay-v1".equals(values.getProperty("format"))||!VERSION.matcher(version).matches())throw new IOException("The core update manifest is invalid.");String current=System.getenv("FABRICNAVIGATOR_VERSION");if(current!=null&&VERSION.matcher(current).matches()&&compareVersion(version,current)<=0)throw new IOException("The offline update must be newer than the installed version "+current+".");targetName="FabricNavigator-Update-"+version+".zip";}else{ZipEntry manifest=zip.getEntry("plugin/plugin.json");if(manifest==null)throw new IOException("The archive is not an Extreme device image package.");String json=new String(readEntry(zip,manifest,262144),"UTF-8"),id=jsonField(json,"id");version=jsonField(json,"version");if(!"extreme-device-images".equals(id)||!PLUGIN_VERSION.matcher(version).matches())throw new IOException("The device image plugin manifest is invalid.");boolean image=false;Enumeration<? extends ZipEntry> entries=zip.entries();while(entries.hasMoreElements()){String name=entries.nextElement().getName();if(name.startsWith("plugin/")&&name.toLowerCase(Locale.ROOT).endsWith(".png")){image=true;break;}}if(!image)throw new IOException("The device image package contains no PNG images.");targetName="FabricNavigator-Extreme-Device-Images-"+version+".zip";}}finally{zip.close();}
 File target=new File(OFFLINE_DIR,targetName);try{Files.move(temporary.toPath(),target.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException ex){Files.move(temporary.toPath(),target.toPath(),StandardCopyOption.REPLACE_EXISTING);}Properties state=new Properties();state.setProperty("state","ready");state.setProperty("version",version);state.setProperty("file",targetName);state.setProperty("digest","sha256:"+sha);state.setProperty("size",Long.toString(size));state.setProperty("uploadedAt",Long.toString(System.currentTimeMillis()));state.setProperty("uploadedBy",actor);if("core".equals(kind)){atomicProperties(new File(STATE_DIR,"offline-update.properties"),state);AuditLog.log(actor,"OFFLINE_UPDATE_UPLOADED",version,request.getRemoteAddr());}else{atomicProperties(new File(STATE_DIR,"plugin-status.properties"),state);atomicProperties(new File(STATE_DIR,"plugin-install.request"),state);AuditLog.log(actor,"DEVICE_IMAGE_PACKAGE_UPLOADED",version,request.getRemoteAddr());}out.print("{\"ok\":true,\"kind\":\""+kind+"\",\"version\":\""+j(version)+"\",\"digest\":\"sha256:"+sha+"\"}");
}catch(Exception ex){temporary.delete();response.setStatus(400);out.print("{\"ok\":false,\"error\":\""+j(clean(ex.getMessage()))+"\"}");}
%>
