<%@ page import="com.nortel.eem.em.security.EdmSecurity" %><%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%
response.setHeader("Cache-Control","no-store");
String error="",next=request.getParameter("next");if(next==null||!next.startsWith("/")||next.startsWith("//"))next="/";
String csrf=EdmSecurity.csrf(session);
if("POST".equalsIgnoreCase(request.getMethod())){
 if(!EdmSecurity.validCsrf(request)){response.setStatus(403);error="Die Sitzung ist abgelaufen. Bitte erneut versuchen.";}
 else {String username=request.getParameter("username"),password=request.getParameter("password");
  try{EdmSecurity.User user=EdmSecurity.login(username,password,request.getRemoteAddr());if(user==null){Thread.sleep(350);error=EdmSecurity.isLoginBlocked(username,request.getRemoteAddr())?"Zu viele Fehlversuche. Anmeldung vorübergehend gesperrt.":"Benutzername oder Passwort ist ungültig.";}else{request.changeSessionId();session.setMaxInactiveInterval(1800);session.setAttribute("edm.auth.user",user.username);session.setAttribute("edm.auth.role",user.role);EdmSecurity.setAuthCookie(response,EdmSecurity.createAuthToken(user.username));response.sendRedirect(next);return;}}
  catch(Exception ex){response.setStatus(500);error="Die Anmeldung ist momentan nicht verfügbar.";}
 }
}
%><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Anmeldung · FabricNavigator</title><script>try{document.documentElement.setAttribute("data-theme",localStorage.getItem("edmTheme")||((window.matchMedia&&matchMedia("(prefers-color-scheme: dark)").matches)?"dark":"light"));}catch(e){document.documentElement.setAttribute("data-theme","light");}</script><link rel="icon" type="image/png" href="/assets/FabricNavigator_modern_favicon.png"><link rel="stylesheet" href="/assets/security.css?v=20260825-146"></head><body class="auth-page"><main class="auth-card"><img src="/assets/FabricNavigator_modern_schwarz.png" alt="FabricNavigator" class="auth-logo auth-logo-light"><img src="/assets/FabricNavigator_modern.png" alt="FabricNavigator" class="auth-logo auth-logo-dark"><h1>Anmelden</h1><p class="muted">Lokale, geschützte Anmeldung für Topologie, Geräteverwaltung und Webterminal.</p><%if(error.length()>0){%><div class="alert error" role="alert"><%=error%></div><%}%><form method="post" autocomplete="on"><input type="hidden" name="csrfToken" value="<%=csrf%>"><input type="hidden" name="next" value="<%=next.replace("&","&amp;").replace("\"","&quot;")%>"><label>Benutzername<input name="username" required maxlength="32" autocomplete="username" autofocus></label><label>Passwort<input name="password" type="password" required maxlength="128" autocomplete="current-password"></label><button type="submit">Anmelden</button></form></main></body></html>
