<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%
response.setStatus(404);
response.setHeader("Cache-Control","no-store");
String requested=(String)request.getAttribute("javax.servlet.error.request_uri");
if(requested==null||requested.trim().length()==0)requested=request.getRequestURI();
String safe=requested.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");
%><!doctype html><html lang="de" data-app="fabricnavigator-error"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>404 · FabricNavigator</title><link rel="icon" type="image/png" href="/assets/FabricNavigator_modern_favicon.png"><script>(function(){try{var language=localStorage.getItem('edmLanguage'),theme=localStorage.getItem('edmTheme');if(language)document.documentElement.lang=language;if(!theme&&window.matchMedia)theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.setAttribute('data-theme',theme||'light');}catch(error){document.documentElement.setAttribute('data-theme','light');}})();</script><link rel="stylesheet" href="/assets/app-shell.css?v=20260828-170"><style>
body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 15% 10%,color-mix(in srgb,var(--fn-accent) 11%,transparent),transparent 42%),var(--fn-bg);color:var(--fn-text);font-family:Arial,Helvetica,sans-serif}.fn-error-card{width:min(100%,720px);padding:38px;border:1px solid color-mix(in srgb,var(--fn-accent) 55%,var(--fn-border));border-top:5px solid var(--fn-accent);border-radius:20px;background:var(--fn-panel);color:var(--fn-text);box-shadow:var(--fn-shadow)}.fn-error-logo{display:block;width:220px;max-width:72%;height:auto;margin:0 0 30px;object-fit:contain}.fn-error-logo-dark{display:none}.fn-error-code{margin:0;color:var(--fn-accent);font-size:13px;font-weight:900;letter-spacing:.16em}.fn-error-card h1{margin:9px 0 12px;color:var(--fn-text);font-size:clamp(32px,6vw,58px)}.fn-error-card p{color:var(--fn-muted);line-height:1.6}.fn-error-path{padding:12px;border:1px solid var(--fn-border);border-radius:10px;background:color-mix(in srgb,var(--fn-accent) 8%,var(--fn-panel));color:var(--fn-text)!important;overflow-wrap:anywhere;font-family:ui-monospace,Consolas,monospace}.fn-error-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.fn-error-actions a{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 18px;border:1px solid var(--fn-accent);border-radius:10px;background:var(--fn-accent);color:#fff;text-decoration:none;font-weight:850}.fn-error-actions a.secondary{border-color:var(--fn-border);background:transparent;color:var(--fn-text)}.fn-error-actions a:focus-visible{outline:3px solid color-mix(in srgb,var(--fn-accent) 28%,transparent);outline-offset:2px}[data-theme="dark"] .fn-error-logo-light{display:none}[data-theme="dark"] .fn-error-logo-dark{display:block}[data-theme="dark"] .fn-error-card{background:#151c2e;border-color:color-mix(in srgb,var(--fn-accent) 62%,#39445b);box-shadow:0 30px 80px rgba(0,0,0,.48)}[data-theme="dark"] .fn-error-path{background:#10182a;border-color:#39445b}[data-theme="light"] .fn-error-card{background:#fff}[data-theme="light"] .fn-error-actions a.secondary:hover{background:#f4eefb}[data-theme="dark"] .fn-error-actions a.secondary:hover{background:#222d46}
</style></head><body><main class="fn-error-card"><img class="fn-error-logo fn-error-logo-light" src="/assets/FabricNavigator_modern_light.png" alt="FabricNavigator"><img class="fn-error-logo fn-error-logo-dark" src="/assets/FabricNavigator_modern.png" alt="FabricNavigator"><p class="fn-error-code">HTTP 404</p><h1 data-de="Seite nicht gefunden" data-en="Page not found">Seite nicht gefunden</h1><p data-de="Die angeforderte FabricNavigator-Seite existiert nicht oder wurde verschoben." data-en="The requested FabricNavigator page does not exist or has been moved.">Die angeforderte FabricNavigator-Seite existiert nicht oder wurde verschoben.</p><p class="fn-error-path"><%=safe%></p><div class="fn-error-actions"><a href="/topology/" data-de="Zur Topologie" data-en="Go to topology">Zur Topologie</a><a class="secondary" href="/devices/" data-de="Zu Devices" data-en="Go to Devices">Zu Devices</a></div></main><script>(function(){var en=(document.documentElement.lang||'de').toLowerCase().indexOf('de')!==0;if(!en)return;document.querySelectorAll('[data-en]').forEach(function(node){node.textContent=node.dataset.en;});})();</script></body></html>
