##############################
# FabricNavigator ACLI config #
##############################
# Version = 999

timeout_val                    22
connect_timeout_val            35
login_timeout_val              30
auto_detect_flg                1
more_paging_flg                1
alias_enable_flg               1
keepalive_timer_val            4
session_timeout_val            600
auto_log_to_file_flg           0
log_path_str                   '/opt/fabricnavigator/data/acli-logs'
auto_log_filename_str          '%Y/%m/%d/%H-%M-%S_<>'
