<%@ page import="com.nortel.eem.em.security.EdmSecurity,com.nortel.eem.em.security.AuditLog" %><%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%!
private static String h(String value){if(value==null)return"";return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
%><%
response.setHeader("Cache-Control","no-store");
String actor=EdmSecurity.currentUser(request);if(actor==null||actor.trim().length()==0){response.sendRedirect("/login.jsp?next=%2Fprofile%2F");return;}
String csrf=EdmSecurity.csrf(session),messageKey="",messageType="",profileRole=EdmSecurity.isAdmin(request)?"admin":"user";
if("POST".equalsIgnoreCase(request.getMethod())){
  if(!EdmSecurity.validCsrf(request)){response.sendError(403);return;}
  try{
    String action=request.getParameter("action");
    if(!"changePassword".equals(action))throw new IllegalArgumentException("invalidAction");
    String current=request.getParameter("currentPassword"),next=request.getParameter("newPassword"),repeat=request.getParameter("repeatPassword");
    if(current==null||next==null||repeat==null||!next.equals(repeat))throw new IllegalArgumentException("passwordMismatch");
    if(EdmSecurity.authenticate(actor,current)==null)throw new SecurityException("currentPasswordInvalid");
    if(current.equals(next))throw new IllegalArgumentException("passwordUnchanged");
    EdmSecurity.resetPassword(actor,next);AuditLog.log(actor,"PASSWORD_CHANGED",actor,request.getRemoteAddr());
    messageKey="passwordSaved";messageType="success";
  }catch(SecurityException ex){messageKey="currentPasswordInvalid";messageType="error";}
   catch(IllegalArgumentException ex){messageKey="passwordMismatch".equals(ex.getMessage())?"passwordMismatch":"passwordRequirements";messageType="error";}
   catch(Exception ex){messageKey="passwordFailed";messageType="error";}
}
%><!doctype html><html lang="de" class="fn-shell-loading" data-app="fabricnavigator-profile" data-fn-user="<%=h(actor)%>" data-fn-role="<%=h(profileRole)%>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Profil · FabricNavigator</title><link rel="icon" type="image/png" href="/assets/FabricNavigator_modern_favicon.png"><script>(function(){try{var language=localStorage.getItem('edmLanguage'),theme=localStorage.getItem('edmTheme');if(language)document.documentElement.lang=language;if(!theme&&window.matchMedia)theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.setAttribute('data-theme',theme||'light');}catch(error){document.documentElement.setAttribute('data-theme','light');}})();</script><link rel="stylesheet" href="/assets/security.css"><link rel="stylesheet" href="/assets/app-shell.css?v=20260828-170"><link rel="stylesheet" href="/assets/user-profile.css?v=20260828-170"></head><body>
<header class="header"><div class="header-inner"><span class="brand-logo"><img class="logo logo-light" src="/assets/FabricNavigator_modern_schwarz.png" alt="FabricNavigator"><img class="logo logo-dark" src="/assets/FabricNavigator_modern.png" alt="FabricNavigator"></span><nav class="nav"><a class="button secondary" href="/devices/">Devices</a><a class="button secondary" href="/topology/">Topologie</a><%if(EdmSecurity.isAdmin(request)){%><a class="button secondary" href="/admin/">Administration</a><%}%><form method="post" action="/logout.jsp"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><button class="button secondary" type="submit">Abmelden</button></form></nav></div></header>
<main class="page fn-profile-page"><section class="hero"><p class="eyebrow" data-profile-text="eyebrow">BENUTZERPROFIL</p><h1 data-profile-text="title">Profil</h1><p data-profile-text="intro">Passe deine persönliche FabricNavigator-Darstellung und deine SSH-Werkzeugleiste an. Diese Einstellungen folgen deinem Benutzerkonto auf andere Browser und Geräte.</p></section>
<nav class="fn-profile-tabs" role="tablist" aria-label="Profilbereiche"><button class="active" type="button" role="tab" aria-selected="true" data-profile-tab="images" data-profile-text="imagesTab">Gerätebilder</button><button type="button" role="tab" aria-selected="false" data-profile-tab="toolbar" data-profile-text="toolbarTab">SSH-Werkzeugleiste</button><button type="button" role="tab" aria-selected="false" data-profile-tab="password" data-profile-text="passwordTab">Passwort ändern</button></nav>
<%if(messageKey.length()>0){%><p class="fn-profile-alert <%=h(messageType)%>" role="status" data-profile-message="<%=h(messageKey)%>"></p><%}%>
<section class="fn-profile-card fn-profile-panel fn-admin-design-images" data-profile-panel="images"><h2 data-profile-text="imagesTitle">Gerätebilder in der Topologie</h2><p class="secret-note" data-profile-text="imagesDescription">Wähle passende Produktfotos oder generische Engine-Bilder für Extreme-Switches.</p><label><span data-profile-text="appearance">Darstellung für Extreme-Switches</span><select id="fn-profile-image-mode"><option value="product" data-profile-text="product">Passende Produktfotos</option><option value="generic" data-profile-text="generic">Generische Engine-Bilder</option></select></label><p class="fn-installed-design-version"><strong data-profile-text="installedVersion">Installierte Designversion:</strong> <span data-profile-version>Wird geladen …</span></p><p class="fn-admin-design-status" role="status"></p></section>
<section class="fn-profile-card fn-profile-panel fn-toolbar-admin-panel" data-profile-panel="toolbar" hidden><h2 data-profile-text="toolbarTitle">SSH-Werkzeugleiste</h2><p class="secret-note" data-profile-text="toolbarDescription">Lege den Standardnamen der SSH-Tabs und eigene Terminal-Kommandos fest.</p><label class="fn-toolbar-mode"><span data-profile-text="tabLabel">SSH-Tab standardmäßig anzeigen als</span><select id="fn-profile-toolbar-label"><option value="ip">IP</option><option value="name" data-profile-text="deviceName">Gerätename</option></select></label><div class="fn-toolbar-rows"></div><div class="fn-toolbar-admin-actions"><button type="button" class="fn-shell-button fn-toolbar-add" data-profile-text="addButton">Button hinzufügen</button><button type="button" class="fn-shell-button fn-toolbar-save" data-profile-text="save">Speichern</button><span class="fn-toolbar-status" role="status"></span></div></section>
<section class="fn-profile-card fn-profile-panel fn-profile-password" data-profile-panel="password" hidden><h2 data-profile-text="passwordTitle">Passwort ändern</h2><p class="secret-note" data-profile-text="passwordDescription">Bestätige dein aktuelles Passwort und verwende anschließend ein neues Passwort mit mindestens 12 Zeichen.</p><form method="post" autocomplete="off" class="fn-profile-password-form"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><input type="hidden" name="action" value="changePassword"><label><span data-profile-text="currentPassword">Aktuelles Passwort</span><input type="password" name="currentPassword" required maxlength="128" autocomplete="current-password"></label><label><span data-profile-text="newPassword">Neues Passwort</span><input type="password" name="newPassword" required minlength="12" maxlength="128" autocomplete="new-password"></label><label><span data-profile-text="repeatPassword">Neues Passwort wiederholen</span><input type="password" name="repeatPassword" required minlength="12" maxlength="128" autocomplete="new-password"></label><div class="fn-profile-password-actions"><button type="submit" class="fn-shell-button" data-profile-text="savePassword">Passwort ändern</button></div></form></section>
</main><script src="/assets/app-shell.js?v=20260828-170"></script><script src="/assets/user-profile.js?v=20260828-170"></script></body></html>
