<%@ page import="java.util.*,java.lang.reflect.*,com.nortel.eem.em.topology.TopologyDiscoveryV7,com.nortel.eem.em.util.SnmpUtilV3,com.nortel.eem.em.security.CredentialVault,com.nortel.eem.em.security.EdmSecurity" %><%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %><%!
private static String j(String value){if(value==null)return "";return value.replace("\\","\\\\").replace("\"","\\\"").replace("\r","").replace("\n","\\n");}
private static boolean privateIp(String value){if(value==null||!value.matches("^[0-9.]{7,15}$"))return false;String[] parts=value.split("\\.",-1);if(parts.length!=4)return false;int[] octets=new int[4];for(int i=0;i<4;i++)try{if(parts[i].length()==0||(parts[i].length()>1&&parts[i].startsWith("0")))return false;octets[i]=Integer.parseInt(parts[i]);if(octets[i]<0||octets[i]>255)return false;}catch(Exception error){return false;}return octets[0]==10||(octets[0]==172&&octets[1]>=16&&octets[1]<=31)||(octets[0]==192&&octets[1]==168);}
private static TopologyDiscoveryV7.Credential credential(String id)throws Exception{Properties value=CredentialVault.getCredential(id);if(!CredentialVault.TYPE_SNMP.equals(value.getProperty("type"))||!"true".equalsIgnoreCase(value.getProperty("enabled","true")))throw new IllegalArgumentException();TopologyDiscoveryV7.Credential result=new TopologyDiscoveryV7.Credential();result.version=value.getProperty("version","");result.community=value.getProperty("roCommunity","");result.user=value.getProperty("username","");result.level=value.getProperty("securityLevel","");result.authProtocol=value.getProperty("authProtocol","");result.authPassword=value.getProperty("v3AuthPassword","");result.privProtocol=value.getProperty("privProtocol","");result.privPassword=value.getProperty("v3PrivPassword","");result.context=value.getProperty("context","");return result;}
private static SnmpUtilV3 connect(String host,List<TopologyDiscoveryV7.Credential> credentials)throws Exception{Method method=TopologyDiscoveryV7.class.getDeclaredMethod("connect",String.class,List.class,long.class);method.setAccessible(true);Object match=method.invoke(new TopologyDiscoveryV7(),host,credentials,System.currentTimeMillis()+9000L);if(match==null)return null;Field field=match.getClass().getDeclaredField("snmp");field.setAccessible(true);return (SnmpUtilV3)field.get(match);}
@SuppressWarnings("unchecked") private static Map<String,String> walk(SnmpUtilV3 snmp,String mib)throws Exception{Method method=TopologyDiscoveryV7.class.getDeclaredMethod("walkMap",SnmpUtilV3.class,String.class);method.setAccessible(true);return (Map<String,String>)method.invoke(null,snmp,mib);}
private static int index(String oid){if(oid==null)return -1;String[] parts=oid.split("\\.");try{return Integer.parseInt(parts[parts.length-1]);}catch(Exception ignored){return -1;}}
private static int type(String value){if(value==null)return -1;java.util.regex.Matcher matcher=java.util.regex.Pattern.compile("(\\d+)").matcher(value);int found=-1;while(matcher.find())try{found=Integer.parseInt(matcher.group(1));}catch(Exception ignored){}return found;}
private static boolean physicalType(int value){return value==6||value==26||value==62||value==69||value==117;}
private static boolean virtualName(String value){String name=value==null?"":value.trim().toLowerCase(Locale.ENGLISH);return name.length()==0||name.matches(".*(?:^|[ _./:-])(vlan|vl|svi|loopback|lo|tunnel|tun|gre|mlt|lag|lacp|trunk|bridge|br|cpu|null|discard)(?:$|[ _./:-]).*");}
private static List<String> ports(SnmpUtilV3 snmp)throws Exception{Map<String,String> names=walk(snmp,"ifName"),descriptions=walk(snmp,"ifDescr"),types=walk(snmp,"ifType");Map<Integer,String> byIndex=new TreeMap<Integer,String>();Map<Integer,Integer> typeByIndex=new HashMap<Integer,Integer>();for(Map.Entry<String,String> item:types.entrySet()){int index=index(item.getKey());if(index>=0)typeByIndex.put(index,type(item.getValue()));}for(Map.Entry<String,String> item:names.entrySet()){int index=index(item.getKey());if(index>=0)byIndex.put(index,item.getValue());}for(Map.Entry<String,String> item:descriptions.entrySet()){int index=index(item.getKey());if(index>=0&&!byIndex.containsKey(index))byIndex.put(index,item.getValue());}LinkedHashSet<String> output=new LinkedHashSet<String>();for(Map.Entry<Integer,String> item:byIndex.entrySet()){Integer interfaceType=typeByIndex.get(item.getKey());String name=item.getValue()==null?"":item.getValue().trim();if(interfaceType==null||!physicalType(interfaceType.intValue())||virtualName(name))continue;if(name.length()<=80)output.add(name);if(output.size()>=256)break;}return new ArrayList<String>(output);}
%><%
response.setHeader("Cache-Control","no-store");response.setHeader("X-Content-Type-Options","nosniff");String actor=EdmSecurity.currentUser(request),host=request.getParameter("host");if(actor==null||actor.trim().length()==0){response.sendError(403);return;}if(!"POST".equalsIgnoreCase(request.getMethod())||!EdmSecurity.validCsrf(request)){response.sendError(403);return;}if(!privateIp(host)){response.sendError(400);return;}
LinkedHashSet<String> ids=new LinkedHashSet<String>();try{String assigned=CredentialVault.getDeviceCredentialId(host,CredentialVault.TYPE_SNMP);if(assigned!=null&&assigned.length()>0)ids.add(assigned);}catch(Exception ignored){}String[] requested=request.getParameterValues("managedCredentialId");if(requested!=null)for(String id:requested)if(id!=null&&id.length()>0&&ids.size()<TopologyDiscoveryV7.MAX_CREDENTIALS)ids.add(id);List<TopologyDiscoveryV7.Credential> credentials=new ArrayList<TopologyDiscoveryV7.Credential>();for(String id:ids)try{credentials.add(credential(id));}catch(Exception ignored){}
SnmpUtilV3 snmp=null;try{if(credentials.isEmpty()){out.print("{\"ok\":true,\"snmp\":false,\"ports\":[]}");return;}snmp=connect(host,credentials);if(snmp==null){out.print("{\"ok\":true,\"snmp\":false,\"ports\":[]}");return;}List<String> values=ports(snmp);StringBuilder json=new StringBuilder("{\"ok\":true,\"snmp\":true,\"ports\":[");for(int i=0;i<values.size();i++){if(i>0)json.append(',');json.append('\"').append(j(values.get(i))).append('\"');}out.print(json.append("]}").toString());}catch(Exception error){out.print("{\"ok\":true,\"snmp\":false,\"ports\":[]}");}finally{if(snmp!=null)try{snmp.closeSession();}catch(Exception ignored){}}
%>
