<%@ page import="java.util.*,java.util.concurrent.TimeUnit,java.io.*,java.nio.charset.StandardCharsets,com.nortel.eem.em.security.CredentialVault,com.nortel.eem.em.security.EdmSecurity,com.nortel.eem.em.security.KnownHostsManager,com.nortel.eem.em.security.AuditLog" %><%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %><%!
private static String j(String s){if(s==null)return "";return s.replace("\\","\\\\").replace("\"","\\\"").replace("\r","").replace("\n","\\n");}
private static String b64(String s){return Base64.getEncoder().encodeToString((s==null?"":s).getBytes(StandardCharsets.UTF_8));}
private static boolean ip(String s){if(s==null||!s.matches("^[0-9.]{7,15}$"))return false;String[] p=s.split("\\.",-1);if(p.length!=4)return false;for(String x:p)try{int n=Integer.parseInt(x);if(n<0||n>255)return false;}catch(Exception e){return false;}return true;}
private static int number(String value,int minimum,int maximum)throws Exception{int n=Integer.parseInt(value);if(n<minimum||n>maximum)throw new IllegalArgumentException("Value outside allowed range");return n;}
private static String run(String host,String action,String vlan,String name,String msti,String isid,String platform)throws Exception{
 String id=CredentialVault.getDeviceCredentialId(host,CredentialVault.TYPE_SSH);if(id==null||id.length()==0)throw new IOException("No SSH credential is assigned");
 Properties c=CredentialVault.getCredential(id);if(!"true".equalsIgnoreCase(c.getProperty("enabled","true")))throw new IOException("Assigned SSH credential is disabled");
 int port=Integer.parseInt(c.getProperty("port","22"));if(!KnownHostsManager.isApproved(host,port))throw new IOException("SSH host key is not approved");
 Process p=new ProcessBuilder("/usr/bin/perl","/opt/fabricnavigator/service-provision.pl").redirectErrorStream(true).start();BufferedWriter w=new BufferedWriter(new OutputStreamWriter(p.getOutputStream(),StandardCharsets.UTF_8));
 String[] values={host,c.getProperty("username",""),c.getProperty("sshPassword",""),c.getProperty("sshPrivateKey",""),c.getProperty("sshKeyPassphrase","")};for(String v:values){w.write(b64(v));w.newLine();}w.write(Integer.toString(port));w.newLine();for(String v:new String[]{action,vlan,name,msti,isid,platform}){w.write(b64(v));w.newLine();}w.close();
 boolean done=p.waitFor(90,TimeUnit.SECONDS);if(!done){p.destroyForcibly();throw new IOException("SSH operation timed out");}BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream(),StandardCharsets.UTF_8));String line,last="";while((line=r.readLine())!=null)last=line;if(last.length()==0)throw new IOException("SSH helper returned no result");return last;
}
%><%
response.setHeader("Cache-Control","no-store");if(!EdmSecurity.isAdmin(request)){response.sendError(403);return;}if(!"POST".equalsIgnoreCase(request.getMethod())||!EdmSecurity.validCsrf(request)){response.sendError(403);return;}
 String action=request.getParameter("action"),vlan=request.getParameter("vlanId"),name=request.getParameter("vlanName"),msti=request.getParameter("msti"),isid=request.getParameter("isid"),platform=request.getParameter("platform");String[] hosts=request.getParameterValues("host");
 try{if(!("precheck".equals(action)||"deploy".equals(action))||!("fabricengine".equals(platform)||"switchengine".equals(platform))||name==null||!name.matches("[A-Za-z0-9_.-]{1,32}")||hosts==null||hosts.length<1||hosts.length>32)throw new IllegalArgumentException();number(vlan,2,4059);number(msti,0,63);number(isid,1,16777214);}catch(Exception invalid){response.sendError(400);return;}
 StringBuilder result=new StringBuilder("{\"results\":[");for(int i=0;i<hosts.length;i++){if(i>0)result.append(',');String host=hosts[i];try{if(!ip(host))throw new IOException("Invalid device IP");String deviceResult=run(host,action,vlan,name,msti,isid,platform);result.append(deviceResult);AuditLog.log(EdmSecurity.currentUser(request),"deploy".equals(action)?"SERVICE_CREATE":"SERVICE_PRECHECK",host+" platform="+platform+" vlan="+vlan+" isid="+isid,request.getRemoteAddr());}catch(Exception ex){result.append("{\"ok\":false,\"host\":\"").append(j(host)).append("\",\"error\":\"").append(j(ex.getMessage())).append("\"}");}}result.append("]}");out.print(result.toString());
%>
